services:
  # Servicio de la aplicación Next.js
  web:
    build:
      context: .       # Carpeta donde está tu Dockerfile
      dockerfile: Dockerfile
    container_name: nextjs_app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/luxeauto
      - NODE_ENV=development
    depends_on:
      - mongo
    volumes:
      - .:/app           # Monta tu proyecto local
      - /app/node_modules

  # Servicio de MongoDB
  mongo:
    image: mongo:7.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

# Volúmenes persistentes
volumes:
  mongo_data:
